// Copyright 2025 fsyyft-go
//
// Licensed under the MIT License. See LICENSE file in the project root for full
// license information.

// 指定 Protocol Buffers 语法版本为 proto3。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/pkg/conf/config.proto

// 指定生成的 Go 代码的包路径和包名。

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterType 定义注册系统类型的枚举。
type RegisterType int32

const (
	// REGISTER_TYPE_UNSPECIFIED 表示未指定，等同于不开启注册。
	RegisterType_REGISTER_TYPE_UNSPECIFIED RegisterType = 0
	// REGISTER_TYPE_NACOS 表示使用 Nacos 作为注册系统。
	RegisterType_REGISTER_TYPE_NACOS RegisterType = 1
)

// Enum value maps for RegisterType.
var (
	RegisterType_name = map[int32]string{
		0: "REGISTER_TYPE_UNSPECIFIED",
		1: "REGISTER_TYPE_NACOS",
	}
	RegisterType_value = map[string]int32{
		"REGISTER_TYPE_UNSPECIFIED": 0,
		"REGISTER_TYPE_NACOS":       1,
	}
)

func (x RegisterType) Enum() *RegisterType {
	p := new(RegisterType)
	*p = x
	return p
}

func (x RegisterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_conf_config_proto_enumTypes[0].Descriptor()
}

func (RegisterType) Type() protoreflect.EnumType {
	return &file_internal_pkg_conf_config_proto_enumTypes[0]
}

func (x RegisterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterType.Descriptor instead.
func (RegisterType) EnumDescriptor() ([]byte, []int) {
	return file_internal_pkg_conf_config_proto_rawDescGZIP(), []int{0}
}

// Config 定义应用程序的配置结构，包含所有子系统的配置信息。
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log 配置应用程序的日志系统。
	Log *Log `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	// Server 配置应用程序的服务器设置。
	Server *Server `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	// Register 配置应用程序的注册系统。
	Register      *Register `protobuf:"bytes,3,opt,name=register,proto3" json:"register,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_internal_pkg_conf_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_conf_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_internal_pkg_conf_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Config) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Config) GetRegister() *Register {
	if x != nil {
		return x.Register
	}
	return nil
}

// Log 定义日志系统的详细配置参数。
type Log struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 指定日志系统类型，支持 logrus 等日志框架。
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// output 指定日志输出的目标路径，可以是文件路径或特殊值（如 stdout）。
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// level 指定日志记录的级别，可选值包括：debug、info、warn、error。
	Level         string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_internal_pkg_conf_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_conf_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_internal_pkg_conf_config_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

// Server 定义服务器相关的配置参数。
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 定义 HTTP 服务器的配置参数。
	Http          *Server_HTTP `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_pkg_conf_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_conf_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_pkg_conf_config_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

// Register 配置应用程序的注册系统。
type Register struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 配置注册系统的类型，使用 RegisterType 枚举。
	Type RegisterType `protobuf:"varint,1,opt,name=type,proto3,enum=internal.conf.RegisterType" json:"type,omitempty"`
	// nacos 配置 Nacos 注册系统的参数。
	Nacos         *Register_Nacos `protobuf:"bytes,2,opt,name=nacos,proto3" json:"nacos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_internal_pkg_conf_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_conf_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_internal_pkg_conf_config_proto_rawDescGZIP(), []int{3}
}

func (x *Register) GetType() RegisterType {
	if x != nil {
		return x.Type
	}
	return RegisterType_REGISTER_TYPE_UNSPECIFIED
}

func (x *Register) GetNacos() *Register_Nacos {
	if x != nil {
		return x.Nacos
	}
	return nil
}

// HTTP 定义 HTTP 服务器的配置参数。
type Server_HTTP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network 指定网络类型，如 tcp、tcp4、tcp6 等。
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// addr 指定服务器监听的地址和端口，格式为 host:port。
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// timeout 定义 HTTP 请求的超时时间。
	Timeout       *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_internal_pkg_conf_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_conf_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_internal_pkg_conf_config_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Nacos 配置 Nacos 注册系统的参数。
type Register_Nacos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerAddr    string                 `protobuf:"bytes,1,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`
	ServerPort    int32                  `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	Client        *Register_Nacos_Client `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register_Nacos) Reset() {
	*x = Register_Nacos{}
	mi := &file_internal_pkg_conf_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register_Nacos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register_Nacos) ProtoMessage() {}

func (x *Register_Nacos) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_conf_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register_Nacos.ProtoReflect.Descriptor instead.
func (*Register_Nacos) Descriptor() ([]byte, []int) {
	return file_internal_pkg_conf_config_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Register_Nacos) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *Register_Nacos) GetServerPort() int32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *Register_Nacos) GetClient() *Register_Nacos_Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// NacosClient 配置 Nacos 客户端的详细参数。
// 用于定制客户端行为，包括超时设置、心跳间隔、缓存策略和日志配置等。
type Register_Nacos_Client struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timeout_ms 指定客户端请求的超时时间，单位为毫秒。
	TimeoutMs int32 `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// beat_interval_ms 指定心跳间隔，用于与 Nacos
	// 服务器保持连接活跃，单位为毫秒。
	BeatIntervalMs int32 `protobuf:"varint,2,opt,name=beat_interval_ms,json=beatIntervalMs,proto3" json:"beat_interval_ms,omitempty"`
	// open_kms 指定是否启用 KMS（密钥管理服务）加密。
	OpenKms bool `protobuf:"varint,3,opt,name=open_kms,json=openKms,proto3" json:"open_kms,omitempty"`
	// cache_dir 指定本地缓存目录的路径，用于存储服务列表等缓存数据。
	CacheDir string `protobuf:"bytes,4,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	// update_thread_num 指定更新线程的数量，用于并发处理服务更新。
	UpdateThreadNum int32 `protobuf:"varint,5,opt,name=update_thread_num,json=updateThreadNum,proto3" json:"update_thread_num,omitempty"`
	// not_load_cache_at_start 指定启动时是否不加载本地缓存，为 true
	// 时忽略缓存。
	NotLoadCacheAtStart bool `protobuf:"varint,6,opt,name=not_load_cache_at_start,json=notLoadCacheAtStart,proto3" json:"not_load_cache_at_start,omitempty"`
	// update_cache_when_empty 指定当服务列表为空时是否更新缓存。
	UpdateCacheWhenEmpty bool `protobuf:"varint,7,opt,name=update_cache_when_empty,json=updateCacheWhenEmpty,proto3" json:"update_cache_when_empty,omitempty"`
	// log_dir 指定客户端日志的输出目录路径。
	LogDir string `protobuf:"bytes,8,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	// log_level 指定客户端日志级别，可选值包括：debug、info、warn、error。
	LogLevel string `protobuf:"bytes,9,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	// namespace_id 命名空间 ID，用于标识不同的命名空间。
	NamespaceId string `protobuf:"bytes,10,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// username 命名空间用户名，用于访问 Nacos 服务。
	Username string `protobuf:"bytes,11,opt,name=username,proto3" json:"username,omitempty"`
	// password 命名空间密码，用于访问 Nacos 服务。
	Password      string `protobuf:"bytes,12,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register_Nacos_Client) Reset() {
	*x = Register_Nacos_Client{}
	mi := &file_internal_pkg_conf_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register_Nacos_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register_Nacos_Client) ProtoMessage() {}

func (x *Register_Nacos_Client) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_conf_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register_Nacos_Client.ProtoReflect.Descriptor instead.
func (*Register_Nacos_Client) Descriptor() ([]byte, []int) {
	return file_internal_pkg_conf_config_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *Register_Nacos_Client) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Register_Nacos_Client) GetBeatIntervalMs() int32 {
	if x != nil {
		return x.BeatIntervalMs
	}
	return 0
}

func (x *Register_Nacos_Client) GetOpenKms() bool {
	if x != nil {
		return x.OpenKms
	}
	return false
}

func (x *Register_Nacos_Client) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *Register_Nacos_Client) GetUpdateThreadNum() int32 {
	if x != nil {
		return x.UpdateThreadNum
	}
	return 0
}

func (x *Register_Nacos_Client) GetNotLoadCacheAtStart() bool {
	if x != nil {
		return x.NotLoadCacheAtStart
	}
	return false
}

func (x *Register_Nacos_Client) GetUpdateCacheWhenEmpty() bool {
	if x != nil {
		return x.UpdateCacheWhenEmpty
	}
	return false
}

func (x *Register_Nacos_Client) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *Register_Nacos_Client) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Register_Nacos_Client) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Register_Nacos_Client) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Register_Nacos_Client) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_internal_pkg_conf_config_proto protoreflect.FileDescriptor

const file_internal_pkg_conf_config_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/pkg/conf/config.proto\x12\rinternal.conf\x1a\x1egoogle/protobuf/duration.proto\"\x92\x01\n" +
	"\x06Config\x12$\n" +
	"\x03log\x18\x01 \x01(\v2\x12.internal.conf.LogR\x03log\x12-\n" +
	"\x06server\x18\x02 \x01(\v2\x15.internal.conf.ServerR\x06server\x123\n" +
	"\bregister\x18\x03 \x01(\v2\x17.internal.conf.RegisterR\bregister\"G\n" +
	"\x03Log\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\"\xa3\x01\n" +
	"\x06Server\x12.\n" +
	"\x04http\x18\x01 \x01(\v2\x1a.internal.conf.Server.HTTPR\x04http\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xb0\x05\n" +
	"\bRegister\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.internal.conf.RegisterTypeR\x04type\x123\n" +
	"\x05nacos\x18\x02 \x01(\v2\x1d.internal.conf.Register.NacosR\x05nacos\x1a\xbd\x04\n" +
	"\x05Nacos\x12\x1f\n" +
	"\vserver_addr\x18\x01 \x01(\tR\n" +
	"serverAddr\x12\x1f\n" +
	"\vserver_port\x18\x02 \x01(\x05R\n" +
	"serverPort\x12<\n" +
	"\x06client\x18\x03 \x01(\v2$.internal.conf.Register.Nacos.ClientR\x06client\x1a\xb3\x03\n" +
	"\x06Client\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x05R\ttimeoutMs\x12(\n" +
	"\x10beat_interval_ms\x18\x02 \x01(\x05R\x0ebeatIntervalMs\x12\x19\n" +
	"\bopen_kms\x18\x03 \x01(\bR\aopenKms\x12\x1b\n" +
	"\tcache_dir\x18\x04 \x01(\tR\bcacheDir\x12*\n" +
	"\x11update_thread_num\x18\x05 \x01(\x05R\x0fupdateThreadNum\x124\n" +
	"\x17not_load_cache_at_start\x18\x06 \x01(\bR\x13notLoadCacheAtStart\x125\n" +
	"\x17update_cache_when_empty\x18\a \x01(\bR\x14updateCacheWhenEmpty\x12\x17\n" +
	"\alog_dir\x18\b \x01(\tR\x06logDir\x12\x1b\n" +
	"\tlog_level\x18\t \x01(\tR\blogLevel\x12!\n" +
	"\fnamespace_id\x18\n" +
	" \x01(\tR\vnamespaceId\x12\x1a\n" +
	"\busername\x18\v \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\f \x01(\tR\bpassword*F\n" +
	"\fRegisterType\x12\x1d\n" +
	"\x19REGISTER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13REGISTER_TYPE_NACOS\x10\x01B;Z9github.com/fsyyft-go/kratos-layout/internal/pkg/conf;confb\x06proto3"

var (
	file_internal_pkg_conf_config_proto_rawDescOnce sync.Once
	file_internal_pkg_conf_config_proto_rawDescData []byte
)

func file_internal_pkg_conf_config_proto_rawDescGZIP() []byte {
	file_internal_pkg_conf_config_proto_rawDescOnce.Do(func() {
		file_internal_pkg_conf_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_conf_config_proto_rawDesc), len(file_internal_pkg_conf_config_proto_rawDesc)))
	})
	return file_internal_pkg_conf_config_proto_rawDescData
}

var file_internal_pkg_conf_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pkg_conf_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_pkg_conf_config_proto_goTypes = []any{
	(RegisterType)(0),             // 0: internal.conf.RegisterType
	(*Config)(nil),                // 1: internal.conf.Config
	(*Log)(nil),                   // 2: internal.conf.Log
	(*Server)(nil),                // 3: internal.conf.Server
	(*Register)(nil),              // 4: internal.conf.Register
	(*Server_HTTP)(nil),           // 5: internal.conf.Server.HTTP
	(*Register_Nacos)(nil),        // 6: internal.conf.Register.Nacos
	(*Register_Nacos_Client)(nil), // 7: internal.conf.Register.Nacos.Client
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
}
var file_internal_pkg_conf_config_proto_depIdxs = []int32{
	2, // 0: internal.conf.Config.log:type_name -> internal.conf.Log
	3, // 1: internal.conf.Config.server:type_name -> internal.conf.Server
	4, // 2: internal.conf.Config.register:type_name -> internal.conf.Register
	5, // 3: internal.conf.Server.http:type_name -> internal.conf.Server.HTTP
	0, // 4: internal.conf.Register.type:type_name -> internal.conf.RegisterType
	6, // 5: internal.conf.Register.nacos:type_name -> internal.conf.Register.Nacos
	8, // 6: internal.conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	7, // 7: internal.conf.Register.Nacos.client:type_name -> internal.conf.Register.Nacos.Client
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_internal_pkg_conf_config_proto_init() }
func file_internal_pkg_conf_config_proto_init() {
	if File_internal_pkg_conf_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_conf_config_proto_rawDesc), len(file_internal_pkg_conf_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pkg_conf_config_proto_goTypes,
		DependencyIndexes: file_internal_pkg_conf_config_proto_depIdxs,
		EnumInfos:         file_internal_pkg_conf_config_proto_enumTypes,
		MessageInfos:      file_internal_pkg_conf_config_proto_msgTypes,
	}.Build()
	File_internal_pkg_conf_config_proto = out.File
	file_internal_pkg_conf_config_proto_goTypes = nil
	file_internal_pkg_conf_config_proto_depIdxs = nil
}
