// Copyright 2025 fsyyft-go
//
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package web

import (
	appbiz "github.com/fsyyft-go/kratos-layout/internal/biz"
	appconf "github.com/fsyyft-go/kratos-layout/internal/conf"
	appdata "github.com/fsyyft-go/kratos-layout/internal/data"
	applog "github.com/fsyyft-go/kratos-layout/internal/log"
	appserver "github.com/fsyyft-go/kratos-layout/internal/server"
	appservice "github.com/fsyyft-go/kratos-layout/internal/service"
)

// Injectors from wire.go:

func wireWeb(conf2 *appconf.Config) (appserver.WebServer, func(), error) {
	logger, cleanup, err := applog.NewLogger(conf2)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := appdata.NewData(logger, conf2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	greeterRepo := appdata.NewGreeterRepo(logger, conf2, dataData)
	greeterUsecase := appbiz.NewGreeterUsecase(logger, conf2, greeterRepo)
	greeterHTTPServer := appservice.NewGreeterService(logger, conf2, greeterUsecase)
	webServer, cleanup3, err := appserver.NewWebServer(logger, conf2, greeterHTTPServer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return webServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
