// Copyright 2025 fsyyft-go
//
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package task

import (
	app_conf "github.com/fsyyft-go/kratos-layout/internal/conf"
	app_log "github.com/fsyyft-go/kratos-layout/internal/log"
	app_task "github.com/fsyyft-go/kratos-layout/internal/task"
)

// Injectors from wire.go:

func wireTask(cfg *app_conf.Config) (app_task.Hello, func(), error) {
	logger, cleanup, err := app_log.NewLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	hello, err := app_task.NewHello(logger, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return hello, func() {
		cleanup()
	}, nil
}
