// Copyright 2025 fsyyft-go
//
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package task

import (
	appconf "github.com/fsyyft-go/kratos-layout/internal/conf"
	applog "github.com/fsyyft-go/kratos-layout/internal/log"
	apptask "github.com/fsyyft-go/kratos-layout/internal/task"
)

// Injectors from wire.go:

func wireTask(cfg *appconf.Config) (apptask.Hello, func(), error) {
	logger, cleanup, err := applog.NewLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	hello, err := apptask.NewHello(logger, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return hello, func() {
		cleanup()
	}, nil
}
